// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: tbox.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TBOX 遥测消息协议
type TelemetryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                // 协议版本号
	MsgType       uint32                 `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"` // 消息类型: 1=心跳, 2=遥测, 3=告警
	Vin           string                 `protobuf:"bytes,3,opt,name=vin,proto3" json:"vin,omitempty"`                         // 车架号
	Power         int32                  `protobuf:"varint,4,opt,name=power,proto3" json:"power,omitempty"`                    // 功率
	Speed         int32                  `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`                    // 速度
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                  // 状态: 0-离线 1-在线
	Lat           float64                `protobuf:"fixed64,7,opt,name=lat,proto3" json:"lat,omitempty"`                       // 纬度
	Lon           float64                `protobuf:"fixed64,8,opt,name=lon,proto3" json:"lon,omitempty"`                       // 经度
	Timestamp     uint64                 `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`            // 时间戳(Unix毫秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryMessage) Reset() {
	*x = TelemetryMessage{}
	mi := &file_tbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryMessage) ProtoMessage() {}

func (x *TelemetryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryMessage.ProtoReflect.Descriptor instead.
func (*TelemetryMessage) Descriptor() ([]byte, []int) {
	return file_tbox_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TelemetryMessage) GetMsgType() uint32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *TelemetryMessage) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *TelemetryMessage) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *TelemetryMessage) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *TelemetryMessage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TelemetryMessage) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *TelemetryMessage) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *TelemetryMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_tbox_proto protoreflect.FileDescriptor

const file_tbox_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tbox.proto\x12\x04tbox\"\xdf\x01\n" +
	"\x10TelemetryMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\rR\amsgType\x12\x10\n" +
	"\x03vin\x18\x03 \x01(\tR\x03vin\x12\x14\n" +
	"\x05power\x18\x04 \x01(\x05R\x05power\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x05R\x05speed\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x10\n" +
	"\x03lat\x18\a \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\b \x01(\x01R\x03lon\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x04R\ttimestampB\x11Z\x0fiot/internal/pbb\x06proto3"

var (
	file_tbox_proto_rawDescOnce sync.Once
	file_tbox_proto_rawDescData []byte
)

func file_tbox_proto_rawDescGZIP() []byte {
	file_tbox_proto_rawDescOnce.Do(func() {
		file_tbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tbox_proto_rawDesc), len(file_tbox_proto_rawDesc)))
	})
	return file_tbox_proto_rawDescData
}

var file_tbox_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tbox_proto_goTypes = []any{
	(*TelemetryMessage)(nil), // 0: tbox.TelemetryMessage
}
var file_tbox_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tbox_proto_init() }
func file_tbox_proto_init() {
	if File_tbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tbox_proto_rawDesc), len(file_tbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tbox_proto_goTypes,
		DependencyIndexes: file_tbox_proto_depIdxs,
		MessageInfos:      file_tbox_proto_msgTypes,
	}.Build()
	File_tbox_proto = out.File
	file_tbox_proto_goTypes = nil
	file_tbox_proto_depIdxs = nil
}
